dist: xenial
sudo: false

language: node_js
node_js:
  - "10"

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run-script build
  - cd dist/angular-assigment
  - cp index.html 404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: dist/angular-assigment
  on:
    branch: master
