dist: xenial

language: node_js
node_js:
  - "stable"

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run-script build
  - cd dist/angular-sapient
  - ls
  - cp index.html 404.html

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY_API
  app: angular-sapient
  on:
    branch: master
