dist: xenial
sudo: false

language: node_js
node_js:
  - "stable"

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run-script build
  - cd dist/angular-sapient
  - ls
  - cp index.html 404.html

deploy:
  provider: heroku
  api_key:
    secure: bc14b625-e6e7-47db-a767-4850235c9401
  app: angular-sapient
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: dist/angular-sapient
  on:
    branch: master
